# Generated by Django 4.1.5 on 2023-06-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_achievement_user_alter_game_internal_name_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(to='games.achievement'),
        ),
    ]
