# Generated by Django 4.1.5 on 2023-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='view_name',
            new_name='folder_name',
        ),
    ]
