# Generated by Django 4.1.5 on 2023-04-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_view_name_game_folder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='folder_name',
            new_name='internal_name',
        ),
    ]
